"use client";
import {useState} from "react";
import {saveMenu,setMenuAvailability} from "@/app/actions/cafe-management";
import {useLang} from "@/i18n/LangProvider";
import ActionForm from "./ActionForm";
import MediaPicker from "./MediaPicker";
import MenuDeleteButton from "./MenuDeleteButton";
export type EditableMenu={id:string;name:string;nameEn:string;price:number|null;available:boolean;photo_url:string|null};
function Fields({item}:{item?:EditableMenu}){const {lang}=useLang();return <><label>{lang==="th"?"ชื่อเมนู":"Menu name (Thai)"}<input name="name" defaultValue={item?.name??""} required maxLength={120}/></label><label>{lang==="th"?"ชื่อภาษาอังกฤษ":"English name"}<input name="nameEn" defaultValue={item?.nameEn??""} maxLength={120}/></label><label>{lang==="th"?"ราคา (บาท)":"Price (THB)"}<input name="price" type="number" min={0} max={100000} step="0.01" defaultValue={item?.price??0} required/></label><MediaPicker label={lang==="th"?"รูปเมนู":"Menu photo"} initialUrl={item?.photo_url}/><label><span><input type="checkbox" name="available" defaultChecked={item?.available??true}/>{lang==="th"?" พร้อมขาย":" Available"}</span></label></>;}
export default function MenuManager({slug,items}:{slug:string;items:EditableMenu[]}){const {lang}=useLang();const [query,setQuery]=useState("");return <section className="feature-card"><h2>{lang==="th"?"จัดการเมนู":"Manage menu"}</h2><details className="mb-5"><summary className="ui-secondary">{lang==="th"?"เพิ่มเมนู":"Add menu item"}</summary><ActionForm reset label={lang==="th"?"เพิ่มเมนู":"Add item"} action={saveMenu}><input type="hidden" name="slug" value={slug}/><Fields/></ActionForm></details>
<label className="search-visible">{lang==="th"?"ค้นหาเมนู":"Find menu item"}<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>
<div className="grid gap-4 mt-5">{items.filter(m=>(m.name+" "+m.nameEn).toLowerCase().includes(query.toLowerCase())).map(item=><article key={item.id} className="border rounded-xl p-4"><div className="flex flex-wrap justify-between gap-3"><h3>{lang==="th"?item.name:item.nameEn||item.name} — ฿{item.price??"—"}</h3><ActionForm label={item.available?(lang==="th"?"พร้อมขาย → เปลี่ยนเป็นหมด":"Available → mark sold out"):(lang==="th"?"หมด → เปลี่ยนเป็นพร้อมขาย":"Sold out → mark available")} action={()=>setMenuAvailability(slug,item.id,!item.available)}>{null}</ActionForm></div><details className="mt-3"><summary className="underline">{lang==="th"?"แก้ไขรายละเอียด":"Edit details"}</summary><ActionForm action={saveMenu}><input type="hidden" name="slug" value={slug}/><input type="hidden" name="id" value={item.id}/><Fields item={item}/></ActionForm><MenuDeleteButton slug={slug} id={item.id}/></details></article>)}</div>
{!items.length&&<p className="mt-4">{lang==="th"?"ยังไม่มีเมนู เพิ่มรายการแรกด้านบน":"No menu items yet. Add the first item above."}</p>}</section>;}
